
 
CREATE TABLE SICOP_ESPECIFICADEGASTO (
EGAS_VAR_IDESPECIFICADEGASTO VARCHAR(13)NOT NULL,
EGAS_VAR_DESCRIPCION VARCHAR(200)
)
GO
ALTER TABLE SICOP_ESPECIFICADEGASTO
	ADD CONSTRAINT  PK_SICOP_ESPECIFICADEGASTO PRIMARY KEY   NONCLUSTERED (EGAS_VAR_IDESPECIFICADEGASTO)
GO

CREATE TABLE SICOP_DOCUMENTO (
DOCU_INT_IDDOCUMENTO INT IDENTITY(1,1) NOT NULL,
DOCU_VAR_NOMBRE VARCHAR(100)
)
GO
ALTER TABLE SICOP_DOCUMENTO
	ADD CONSTRAINT  PK_DOCUMENTO PRIMARY KEY   NONCLUSTERED (DOCU_INT_IDDOCUMENTO)
GO


CREATE TABLE SICOP_META_ESPECIFICADEGASTO (
MEGA_VAR_IDMETA VARCHAR(4)NOT NULL,
EGAS_IDESPECIFICADEGASTO VARCHAR(13)NOT NULL,
MEGA_DEC_PIM DECIMAL(10,3)
)
GO
ALTER TABLE SICOP_META_ESPECIFICADEGASTO
	ADD CONSTRAINT  PK_SICOP_META_ESPECIFICADEGASTO PRIMARY KEY   NONCLUSTERED (MEGA_VAR_IDMETA ASC, EGAS_IDESPECIFICADEGASTO ASC)
GO


CREATE TABLE SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES (
MEGM_INT_IDMODIFICACION INT IDENTITY(1,1) NOT NULL,
META_VCH_IDMETA VARCHAR(4)NOT NULL,
EGAS_IDESPECIFICADEGASTO VARCHAR(13)NOT NULL,
MEGM_DEC_PIMMODIFICADO DECIMAL(10,3)
)
GO
ALTER TABLE SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES
	ADD CONSTRAINT  PK_SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES PRIMARY KEY   NONCLUSTERED (MEGM_INT_IDMODIFICACION ASC,META_VCH_IDMETA ASC, EGAS_IDESPECIFICADEGASTO ASC)
GO 

CREATE TABLE SICOP_META (
META_VCH_IDMETA VARCHAR(4)NOT NULL,
META_VAR_DESCRIPCION VARCHAR(50)
)
GO
ALTER TABLE SICOP_META
	ADD CONSTRAINT  PK_META PRIMARY KEY   NONCLUSTERED (META_VCH_IDMETA)
GO

CREATE TABLE SICOP_CONTROLPRESUPUESTAL
(
CPRE_INT_IDCONTROLPRESUPUESTAL INT IDENTITY(1,1)NOT NULL,
EGAS_VAR_IDESPECIFICADEGASTO VARCHAR(13) NOT NULL,
DOCU_INT_IDDOCUMENTO INT NOT NULL,
CPRE_VAR_NRODOCUMENTO VARCHAR(10),
CPRE_DAT_FECHAINGRESO DATETIME,
CPRE_VAR_NROCOMPROBANTEPAGO VARCHAR(10), 
CPRE_VAR_NROSIAF VARCHAR(10), 
CPRE_DAT_FECHAGIRO DATETIME, 
CPRE_DAT_FECHAPAGO DATETIME,
CPRE_VAR_CONCEPTOESPECIFICADEGASTO VARCHAR(200),
CPRE_VAR_DETALLEESPECIFICADEGASTO VARCHAR(200)
)
GO
ALTER TABLE SICOP_CONTROLPRESUPUESTAL
	ADD CONSTRAINT  PK_SICOP_CONTROLPRESUPUESTAL PRIMARY KEY   NONCLUSTERED (CPRE_INT_IDCONTROLPRESUPUESTAL ASC,EGAS_VAR_IDESPECIFICADEGASTO ASC )
GO

--DROP TABLE DETALLECONTROLPRESUPUESTAL
CREATE TABLE SICOP_DETALLECONTROLPRESUPUESTAL
(
CPRE_INT_IDCONTROLPRESUPUESTAL INT NOT NULL,
EGAS_VAR_IDESPECIFICADEGASTO VARCHAR(13) NOT NULL,
META_VAR_IDMETA VARCHAR(4)NOT NULL,
DCPR_DEC_IMPORTE DECIMAL(10,3)

)
GO

ALTER TABLE SICOP_DETALLECONTROLPRESUPUESTAL
	ADD CONSTRAINT  PK_SICOP_DETALLECONTROLPRESUPUESTAL PRIMARY KEY   NONCLUSTERED (CPRE_INT_IDCONTROLPRESUPUESTAL ASC,EGAS_VAR_IDESPECIFICADEGASTO ASC , META_VAR_IDMETA ASC)
GO

ALTER TABLE SICOP_CONTROLPRESUPUESTAL
	ADD CONSTRAINT  FK_SICOP_CONTROLPRESUPUESTAL_VS_SICOP_DOCUMENTO FOREIGN KEY (DOCU_INT_IDDOCUMENTO) REFERENCES SICOP_DOCUMENTO (DOCU_INT_IDDOCUMENTO)
GO
ALTER TABLE SICOP_CONTROLPRESUPUESTAL
	ADD CONSTRAINT  FK_SICOP_CONTROLPRESUPUESTAL_VS_SICOP_ESPECIFICADEGASTO FOREIGN KEY (EGAS_VAR_IDESPECIFICADEGASTO) REFERENCES SICOP_ESPECIFICADEGASTO(EGAS_VAR_IDESPECIFICADEGASTO)
GO

ALTER TABLE SICOP_DETALLECONTROLPRESUPUESTAL
	ADD CONSTRAINT  FK_SICOP_DETALLECONTROLPRESUPUESTAL_VS_SICOP_CONTROLPRESUPUESTAL FOREIGN KEY (CPRE_INT_IDCONTROLPRESUPUESTAL,EGAS_VAR_IDESPECIFICADEGASTO) REFERENCES SICOP_CONTROLPRESUPUESTAL(CPRE_INT_IDCONTROLPRESUPUESTAL,EGAS_VAR_IDESPECIFICADEGASTO)
		
		
GO
ALTER TABLE SICOP_DETALLECONTROLPRESUPUESTAL
	ADD CONSTRAINT  FK_SICOP_DETALLECONTROLPRESUPUESTAL_VS_SICOP_META FOREIGN KEY (META_VCH_IDMETA) REFERENCES SICOP_META(META_VCH_IDMETA)
		
		
GO

