--------------------------------------CONSULTA COMPLETA--------------------------------------------------
CREATE PROCEDURE USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
AS

SET NOCOUNT OFF;

CREATE TABLE #TABLE_TEMP (
CPRE_INT_IDCONTROLPRESUPUESTAL INT,
DOCU_VCH_NOMBRE VARCHAR(100),
CPRE_VCH_NRODOCUMENTO VARCHAR(10),
CPRE_DAT_FECHAINGRESO DATETIME,
CPRE_VCH_NROCOMPROBANTEPAGO VARCHAR(10), 
CPRE_VCH_NROSIAF VARCHAR(10), 
CPRE_DAT_FECHAGIRO DATETIME, 
CPRE_DAT_FECHAPAGO DATETIME,
CPRE_VCH_DETALLEESPECIFICADEGASTO VARCHAR(200),
CPRE_VCH_CONCEPTOESPECIFICADEGASTO VARCHAR(200),
EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13),
CPRE_VCH_PARTIDACONTABLE VARCHAR(20),
META_DEC_META_34 DECIMAL(10,3),
META_DEC_META_62 DECIMAL(10,3),
META_DEC_META_63 DECIMAL(10,3),
META_DEC_TOTAL DECIMAL(10,3)
);
INSERT INTO #TABLE_TEMP(
CPRE_INT_IDCONTROLPRESUPUESTAL ,
DOCU_VCH_NOMBRE ,
CPRE_VCH_NRODOCUMENTO ,
CPRE_DAT_FECHAINGRESO ,
CPRE_VCH_NROCOMPROBANTEPAGO , 
CPRE_VCH_NROSIAF , 
CPRE_DAT_FECHAGIRO , 
CPRE_DAT_FECHAPAGO ,
CPRE_VCH_DETALLEESPECIFICADEGASTO,
CPRE_VCH_CONCEPTOESPECIFICADEGASTO ,
EGAS_VCH_IDESPECIFICADEGASTO ,
CPRE_VCH_PARTIDACONTABLE,
META_DEC_META_34 ,
META_DEC_META_62  ,
META_DEC_META_63 ,
META_DEC_TOTAL
)
SELECT 
CP.CPRE_INT_IDCONTROLPRESUPUESTAL AS 'ID',
DOC.DOCU_VCH_NOMBRE  AS 'DOC.',
CP.CPRE_VCH_NRODOCUMENTO AS 'NRO.',
CP.CPRE_DAT_FECHAINGRESO AS 'FECHA DE PRESENTACION',
CP.CPRE_VCH_NROCOMPROBANTEPAGO AS 'C/P', 
CP.CPRE_VCH_NROSIAF AS 'SIAF', 
CP.CPRE_DAT_FECHAGIRO AS 'FECHA DE GIRO', 
CP.CPRE_DAT_FECHAPAGO AS 'FECHA DE PAGO',
CP.CPRE_VCH_DETALLEESPECIFICADEGASTO  AS 'DETALLE',
CP.CPRE_VCH_CONCEPTOESPECIFICADEGASTO AS 'CONCEPTO' ,
EGA.EGAS_VCH_IDESPECIFICADEGASTO AS 'PARTIDA ESPECÍFICA',
CPRE_VCH_PARTIDACONTABLE AS 'PARTIDA CONTABLE',
 (SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO  AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0034'),
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0062'),
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0063'),
------------------------+++++++++++++TOTAL++++---------------------------------------
((SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO  AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0034') +
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0062') +
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0063'))

 	FROM dbo.SICOP_CONTROLPRESUPUESTAL CP,
		 dbo.SICOP_DOCUMENTO DOC,
		 dbo.SICOP_ESPECIFICADEGASTO EGA
		 WHERE  CP.EGAS_VCH_IDESPECIFICADEGASTO =EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
		 		CP.DOCU_INT_IDDOCUMENTO =DOC.DOCU_INT_IDDOCUMENTO ;
		 		
SELECT * FROM #TABLE_TEMP;
DROP TABLE #TABLE_TEMP;
GO


-----------------------------------------------------------------------------------------------

--/////////////////////////////////////////////////////////
--USP_S_SICOP_META_ESPECIFICADEGASTO_REPORT
--/////////////////////////////////////////////////////////

IF OBJECT_ID ( 'USP_S_SICOP_META_ESPECIFICADEGASTO_REPORT', 'P' ) IS NOT NULL 
    DROP PROCEDURE USP_S_SICOP_META_ESPECIFICADEGASTO_REPORT
go
CREATE PROCEDURE [dbo].[USP_S_SICOP_META_ESPECIFICADEGASTO_REPORT]
	@_META_VCH_IDMETA VARCHAR(4)
	AS
SET NOCOUNT OFF;
CREATE TABLE #TABLE_TEMP_E (
META_VCH_IDMETA VARCHAR(4),
EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13),
MEGA_DEC_PIM DECIMAL(10,3),
ENERO DECIMAL(10,3),
FEBRERO DECIMAL(10,3),
MARZO DECIMAL(10,3),
ABRIL DECIMAL(10,3),
MAYO DECIMAL(10,3),
JUNIO DECIMAL(10,3),
JULIO DECIMAL(10,3),
AGOSTO DECIMAL(10,3),
SEPTIEMBRE DECIMAL(10,3),
OCTUBRE DECIMAL(10,3),
NOVIEMBRE DECIMAL(10,3),
DICIEMBRE DECIMAL(10,3),
TOTALEJECUTADO DECIMAL(10,3),
SADOEJERCICIO DECIMAL(10,3));

INSERT INTO #TABLE_TEMP_E(
META_VCH_IDMETA ,
EGAS_VCH_IDESPECIFICADEGASTO ,
MEGA_DEC_PIM ,
ENERO ,
FEBRERO ,
MARZO ,
ABRIL ,
MAYO ,
JUNIO ,
JULIO ,
AGOSTO ,
SEPTIEMBRE ,
OCTUBRE ,
NOVIEMBRE ,
DICIEMBRE ,
TOTALEJECUTADO ,
SADOEJERCICIO )
SELECT META_VCH_IDMETA ,
EGAS_VCH_IDESPECIFICADEGASTO ,
MEGA_DEC_PIM ,
ISNULL(
(SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=1 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--ENE

ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=2 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--FEB
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=3 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--MAR
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=4 	--ABRIL				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=5				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--MAY
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=6 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--JUN
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=7 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--JUL
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=8 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--AGO
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=9 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--SET
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=10 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--OCT
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=11 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--NOV
ISNULL((SELECT  SUM( DCP.DCPR_DEC_IMPORTE)AS DCPR_DEC_IMPORTE
	  	    	   	FROM SICOP_CONTROLPRESUPUESTAL CP,
			   SICOP_DETALLECONTROLPRESUPUESTAL DCP
			   WHERE DCP.CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=CP.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.EGAS_VCH_IDESPECIFICADEGASTO=MEGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			         DCP.META_VCH_IDMETA=MEGA.META_VCH_IDMETA AND
					MONTH(CP.CPRE_DAT_FECHAINGRESO)=12 				
			         GROUP BY MONTH(CP.CPRE_DAT_FECHAINGRESO)),0) ,--DIC
0,--EJE
0--SALDO
FROM SICOP_META_ESPECIFICADEGASTO MEGA
	WHERE MEGA.META_VCH_IDMETA=@_META_VCH_IDMETA 
	
--UPDATE TOTALEJECUTADO
  	UPDATE #TABLE_TEMP_E SET
 		TOTALEJECUTADO = ENERO +FEBRERO +MARZO +ABRIL +MAYO +JUNIO +JULIO +AGOSTO +SEPTIEMBRE +OCTUBRE +NOVIEMBRE +DICIEMBRE
 	FROM #TABLE_TEMP_E 
 
--UPDATE SALDOEJERCICIO
 	UPDATE #TABLE_TEMP_E SET
 		SADOEJERCICIO=(MEGA_DEC_PIM-TOTALEJECUTADO)
 	FROM #TABLE_TEMP_E 
 	
SELECT * FROM #TABLE_TEMP_E;
DROP TABLE #TABLE_TEMP_E;

EXEC USP_S_SICOP_META_ESPECIFICADEGASTO_REPORT '0034'

-------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------

--// CRUD - TABLAS NECESARIAS PARA FUNCIONAMIENTO DE VS //---

-------------------------------------------------------------------------
-- TB. SICOP_ESPECIFICADEGASTO
-------------------------------------------------------------------------

create procedure USP_A_SICOP_ESPECIFICADEGASTO
(
	@EGAS_VCH_IDESPECIFICADEGASTO varchar(13),
	@EGAS_VCH_DESCRIPCION varchar(200)
)
as
insert into SICOP_ESPECIFICADEGASTO(EGAS_VCH_IDESPECIFICADEGASTO, EGAS_VCH_DESCRIPCION) 
values(@EGAS_VCH_IDESPECIFICADEGASTO,@EGAS_VCH_DESCRIPCION)
go

create procedure USP_U_SICOP_ESPECIFICADEGASTO
(
	@EGAS_VCH_IDESPECIFICADEGASTO varchar(13),
	@EGAS_VCH_DESCRIPCION varchar(200)
)
as update SICOP_ESPECIFICADEGASTO 
set 
	EGAS_VCH_IDESPECIFICADEGASTO = @EGAS_VCH_IDESPECIFICADEGASTO,
	EGAS_VCH_DESCRIPCION = @EGAS_VCH_DESCRIPCION
where SICOP_ESPECIFICADEGASTO.EGAS_VCH_IDESPECIFICADEGASTO = @EGAS_VCH_IDESPECIFICADEGASTO
go


create procedure USP_D_SICOP_ESPECIFICADEGASTO
(
 @EGAS_VCH_IDESPECIFICADEGASTO varchar(13)
)
as
delete from SICOP_ESPECIFICADEGASTO
where EGAS_VCH_IDESPECIFICADEGASTO = @EGAS_VCH_IDESPECIFICADEGASTO
go


create procedure  USP_S_SICOP_ESPECIFICADEGASTO
as
select * from SICOP_ESPECIFICADEGASTO
go

-------------------------------------------------------------------------
-- TB. SICOP_META
-------------------------------------------------------------------------

create procedure USP_S_SICOP_META
as
select * from SICOP_META
go

-------------------------------------------------------------------------
-- TB. SICOP_DOCUMENTO
-------------------------------------------------------------------------

create procedure USP_S_SICOP_DOCUMENTO
as
select * from SICOP_DOCUMENTO
go


-------------------------------------------------------------------------
-- TB. SICOP_META_ESPECIFICADEGASTO
-------------------------------------------------------------------------

create procedure USP_A_SICOP_META_ESPECIFICADEGASTO
(
	@META_VCH_IDMETA varchar(4),
	@EGAS_VCH_IDESPECIFICADEGASTO varchar(13),
	@MEGA_VCH_ANIO varchar(4),
	@MEGA_DEC_PIM decimal(10,3)

)
as
insert into SICOP_META_ESPECIFICADEGASTO(META_VCH_IDMETA, EGAS_VCH_IDESPECIFICADEGASTO, MEGA_VCH_ANIO,MEGA_DEC_PIM) 
values(@META_VCH_IDMETA,@EGAS_VCH_IDESPECIFICADEGASTO, @MEGA_VCH_ANIO,@MEGA_DEC_PIM)
go
-------------------------------------------------------------------------
-- TB. SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES
-------------------------------------------------------------------------

create procedure USP_A_SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES
(
	@META_VCH_IDMETA varchar(4),
	@EGAS_VCH_IDESPECIFICADEGASTO varchar(13),
	@MEGM_DEC_PIMMODIFICADO decimal(10,3)
)
as
insert into SICOP_META_ESPECIFICADEGASTO_MODIFICACIONES
(META_VCH_IDMETA, EGAS_VCH_IDESPECIFICADEGASTO, MEGM_DEC_PIMMODIFICADO) 
values(@META_VCH_IDMETA,@EGAS_VCH_IDESPECIFICADEGASTO, @MEGM_DEC_PIMMODIFICADO)
go

-------------------------------------------------------------------------
-- TB. SICOP_CONTROLPRESUPUESTAL
-------------------------------------------------------------------------

create procedure USP_A_SICOP_CONTROLPRESUPUESTAL
(
	@EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13),
	@DOCU_INT_IDDOCUMENTO VARCHAR(13),
	@CPRE_VCH_NRODOCUMENTO VARCHAR(10),
	@CPRE_DAT_FECHAINGRESO DATETIME,
	@CPRE_VCH_NROCOMPROBANTEPAGO VARCHAR(10),
	@CPRE_VCH_NROSIAF VARCHAR(10),
	@CPRE_DAT_FECHAGIRO DATETIME,
	@CPRE_DAT_FECHAPAGO DATETIME,
	@CPRE_VCH_CONCEPTOESPECIFICADEGASTO VARCHAR(200),
	@CPRE_VCH_DETALLEESPECIFICADEGASTO VARCHAR(200),
	@CPRE_VCH_PARTIDACONTABLE VARCHAR(20)
)
as
insert into SICOP_CONTROLPRESUPUESTAL
(EGAS_VCH_IDESPECIFICADEGASTO, DOCU_INT_IDDOCUMENTO, CPRE_VCH_NRODOCUMENTO, CPRE_DAT_FECHAINGRESO,
CPRE_VCH_NROCOMPROBANTEPAGO,CPRE_VCH_NROSIAF,CPRE_DAT_FECHAGIRO,CPRE_DAT_FECHAPAGO,CPRE_VCH_CONCEPTOESPECIFICADEGASTO,
CPRE_VCH_DETALLEESPECIFICADEGASTO,CPRE_VCH_PARTIDACONTABLE) 
values(@EGAS_VCH_IDESPECIFICADEGASTO,@DOCU_INT_IDDOCUMENTO, @CPRE_VCH_NRODOCUMENTO, @CPRE_DAT_FECHAINGRESO,
@CPRE_VCH_NROCOMPROBANTEPAGO,@CPRE_VCH_NROSIAF,@CPRE_DAT_FECHAGIRO,@CPRE_DAT_FECHAPAGO,@CPRE_VCH_CONCEPTOESPECIFICADEGASTO,
@CPRE_VCH_DETALLEESPECIFICADEGASTO,@CPRE_VCH_PARTIDACONTABLE)
go


create procedure USP_U_SICOP_CONTROLPRESUPUESTAL
(
	@CPRE_INT_IDCONTROLPRESUPUESTAL INT,
	@EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13),
	@DOCU_INT_IDDOCUMENTO VARCHAR(13),
	@CPRE_VCH_NRODOCUMENTO VARCHAR(10),
	@CPRE_DAT_FECHAINGRESO DATETIME,
	@CPRE_VCH_NROCOMPROBANTEPAGO VARCHAR(10),
	@CPRE_VCH_NROSIAF VARCHAR(10),
	@CPRE_DAT_FECHAGIRO DATETIME,
	@CPRE_DAT_FECHAPAGO DATETIME,
	@CPRE_VCH_CONCEPTOESPECIFICADEGASTO VARCHAR(200),
	@CPRE_VCH_DETALLEESPECIFICADEGASTO VARCHAR(200),
	@CPRE_VCH_PARTIDACONTABLE VARCHAR(20)
)
as update SICOP_CONTROLPRESUPUESTAL 
set 
	EGAS_VCH_IDESPECIFICADEGASTO = @EGAS_VCH_IDESPECIFICADEGASTO,
	DOCU_INT_IDDOCUMENTO = @DOCU_INT_IDDOCUMENTO,
	CPRE_VCH_NRODOCUMENTO = @CPRE_VCH_NRODOCUMENTO,
	CPRE_DAT_FECHAINGRESO = @CPRE_DAT_FECHAINGRESO,
	CPRE_VCH_NROCOMPROBANTEPAGO = @CPRE_VCH_NROCOMPROBANTEPAGO,
	CPRE_VCH_NROSIAF = @CPRE_VCH_NROSIAF,
	CPRE_DAT_FECHAGIRO = @CPRE_DAT_FECHAGIRO,
	CPRE_DAT_FECHAPAGO = @CPRE_DAT_FECHAPAGO,
	CPRE_VCH_CONCEPTOESPECIFICADEGASTO = @CPRE_VCH_CONCEPTOESPECIFICADEGASTO,
	CPRE_VCH_DETALLEESPECIFICADEGASTO = @CPRE_VCH_DETALLEESPECIFICADEGASTO,
	CPRE_VCH_PARTIDACONTABLE = @CPRE_VCH_PARTIDACONTABLE
where SICOP_CONTROLPRESUPUESTAL .CPRE_INT_IDCONTROLPRESUPUESTAL = @CPRE_INT_IDCONTROLPRESUPUESTAL
go


-------------------------------------------------------------------------
-- TB. SICOP_DETALLECONTROLPRESUPUESTAL
-------------------------------------------------------------------------

create procedure USP_A_SICOP_DETALLECONTROLPRESUPUESTAL
(
	@CPRE_INT_IDCONTROLPRESUPUESTAL INT,
	@EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13),
	@META_VCH_IDMETA VARCHAR(4),
	@DCPR_DEC_IMPORTE DECIMAL(10,3)
)
as
insert into SICOP_DETALLECONTROLPRESUPUESTAL
(CPRE_INT_IDCONTROLPRESUPUESTAL,EGAS_VCH_IDESPECIFICADEGASTO, META_VCH_IDMETA, DCPR_DEC_IMPORTE) 
values(@CPRE_INT_IDCONTROLPRESUPUESTAL,@EGAS_VCH_IDESPECIFICADEGASTO,@META_VCH_IDMETA, @DCPR_DEC_IMPORTE)
go

-------------------------------------------------------------------------
-- TB. SICOP_USUARIO
-------------------------------------------------------------------------
create procedure USP_L_SICOP_USUARIO
@usu varchar(50),
@password varchar(50)
as
select * from SICOP_USUARIO where SICOP_USUARIO.USU_VCH_USUARIO = @usu and SICOP_USUARIO.USU_VCH_PASSWORD = @password 
go
