
--EXEC USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
--/////////////////////////////////////////////////////////
--USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
--/////////////////////////////////////////////////////////
IF OBJECT_ID ( 'USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT', 'P' ) IS NOT NULL 
    DROP PROCEDURE USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
go
CREATE PROCEDURE [dbo].[USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT]
	--ATRIBUTES OF TABLA SICOP_CONTROLPRESUPUESTAL WITH SICOP_DETALLECONTROLPRESUPUESTAL

	AS
/*
	NOMBRE				: USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
	DESCRIPCION			: REPORTE DE GASTOS ESPECIFICOS CON SU DETALLE
	FECHA				: 04-09-2015
	AUTOR				: TEOFILO CHAMBILLA AQUINO
	ARGUMENTOS			:
	FEC. MODIFIC		: 
	AUTOR MODIFIC		: 
	CAMBIOS IMPORTANTE	: 
*/
SET NOCOUNT OFF;
SELECT 
CP.CPRE_INT_IDCONTROLPRESUPUESTAL ,
EGA.EGAS_VCH_IDESPECIFICADEGASTO ,
EGA.EGAS_VCH_DESCRIPCION ,
DOC.DOCU_VCH_NOMBRE  ,
CP.CPRE_VCH_NRODOCUMENTO ,
CP.CPRE_DAT_FECHAINGRESO ,
CP.CPRE_VCH_NROCOMPROBANTEPAGO , 
CP.CPRE_VCH_NROSIAF , 
CP.CPRE_DAT_FECHAGIRO , 
CP.CPRE_DAT_FECHAPAGO ,
CP.CPRE_VCH_CONCEPTOESPECIFICADEGASTO ,
CP.CPRE_VCH_DETALLEESPECIFICADEGASTO 

	
	FROM dbo.SICOP_CONTROLPRESUPUESTAL CP,
		 dbo.SICOP_DOCUMENTO DOC,
		 dbo.SICOP_ESPECIFICADEGASTO EGA
		 WHERE  CP.EGAS_VCH_IDESPECIFICADEGASTO =EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
		 		CP.DOCU_INT_IDDOCUMENTO =DOC.DOCU_INT_IDDOCUMENTO 


GO