
--EXEC USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
--/////////////////////////////////////////////////////////
--USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
--/////////////////////////////////////////////////////////
IF OBJECT_ID ( 'USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT', 'P' ) IS NOT NULL 
    DROP PROCEDURE USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
go
CREATE PROCEDURE [dbo].[USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT]
	--ATRIBUTES OF TABLA SICOP_CONTROLPRESUPUESTAL WITH SICOP_DETALLECONTROLPRESUPUESTAL

	AS
/*
	NOMBRE				: USP_S_SICOP_CONTROLPRESUPUESTAL_REPORT
	DESCRIPCION			: REPORTE DE GASTOS ESPECIFICOS CON SU DETALLE
	FECHA				: 04-09-2015
	AUTOR				: TEOFILO CHAMBILLA AQUINO
	ARGUMENTOS			:
	FEC. MODIFIC		: 
	AUTOR MODIFIC		: 
	CAMBIOS IMPORTANTE	: 
*/
SET NOCOUNT OFF;

CREATE TABLE #TABLE_TEMP (
CPRE_INT_IDCONTROLPRESUPUESTAL INT,
EGAS_VCH_IDESPECIFICADEGASTO VARCHAR(13) ,
EGAS_VCH_DESCRIPCION VARCHAR(200),
DOCU_VCH_NOMBRE VARCHAR(100),
CPRE_VCH_NRODOCUMENTO VARCHAR(10),
CPRE_DAT_FECHAINGRESO DATETIME,
CPRE_VCH_NROCOMPROBANTEPAGO VARCHAR(10), 
CPRE_VCH_NROSIAF VARCHAR(10), 
CPRE_DAT_FECHAGIRO DATETIME, 
CPRE_DAT_FECHAPAGO DATETIME,
CPRE_VCH_CONCEPTOESPECIFICADEGASTO VARCHAR(200),
CPRE_VCH_DETALLEESPECIFICADEGASTO VARCHAR(200),
META_VCH_META_34 DECIMAL(10,3),
META_VCH_META_62 DECIMAL(10,3),
META_VCH_META_63 DECIMAL(10,3)
);
INSERT INTO #TABLE_TEMP(
CPRE_INT_IDCONTROLPRESUPUESTAL ,
EGAS_VCH_IDESPECIFICADEGASTO ,
EGAS_VCH_DESCRIPCION ,
DOCU_VCH_NOMBRE ,
CPRE_VCH_NRODOCUMENTO ,
CPRE_DAT_FECHAINGRESO ,
CPRE_VCH_NROCOMPROBANTEPAGO , 
CPRE_VCH_NROSIAF , 
CPRE_DAT_FECHAGIRO , 
CPRE_DAT_FECHAPAGO ,
CPRE_VCH_CONCEPTOESPECIFICADEGASTO ,
CPRE_VCH_DETALLEESPECIFICADEGASTO,
META_VCH_META_34  ,
META_VCH_META_62  ,
META_VCH_META_63 
)
SELECT 
CP.CPRE_INT_IDCONTROLPRESUPUESTAL ,
EGA.EGAS_VCH_IDESPECIFICADEGASTO ,
EGA.EGAS_VCH_DESCRIPCION ,
DOC.DOCU_VCH_NOMBRE  ,
CP.CPRE_VCH_NRODOCUMENTO ,
CP.CPRE_DAT_FECHAINGRESO ,
CP.CPRE_VCH_NROCOMPROBANTEPAGO , 
CP.CPRE_VCH_NROSIAF , 
CP.CPRE_DAT_FECHAGIRO , 
CP.CPRE_DAT_FECHAPAGO ,
CP.CPRE_VCH_CONCEPTOESPECIFICADEGASTO ,
CP.CPRE_VCH_DETALLEESPECIFICADEGASTO  ,
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO  AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0034'),
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0062'),
(SELECT DCPR_DEC_IMPORTE   
		FROM SICOP_DETALLECONTROLPRESUPUESTAL 
		WHERE EGAS_VCH_IDESPECIFICADEGASTO=EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
			CPRE_INT_IDCONTROLPRESUPUESTAL=CP.CPRE_INT_IDCONTROLPRESUPUESTAL  AND
			META_VCH_IDMETA='0063')
 	FROM dbo.SICOP_CONTROLPRESUPUESTAL CP,
		 dbo.SICOP_DOCUMENTO DOC,
		 dbo.SICOP_ESPECIFICADEGASTO EGA
		 WHERE  CP.EGAS_VCH_IDESPECIFICADEGASTO =EGA.EGAS_VCH_IDESPECIFICADEGASTO AND
		 		CP.DOCU_INT_IDDOCUMENTO =DOC.DOCU_INT_IDDOCUMENTO ;
		 		
SELECT * FROM #TABLE_TEMP;
DROP TABLE #TABLE_TEMP;
GO